import { FooterLinks } from "@/sections/Footer/components/FooterLinks";

export const FooterContent = () => {
  return (
    <div className="relative items-center box-border caret-transparent flex justify-center break-words pt-[60px] pb-0 px-5 border-t border-solid border-white/20 md:px-[50px] md:py-[100px]">
      <div className="box-border caret-transparent grow max-w-[1140px] break-words mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
        <div className="box-border caret-transparent break-words before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
          <div className="box-border caret-transparent float-left min-h-px break-words w-full mx-auto md:w-[83%] md:mx-0 before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
            <div className="box-border caret-transparent break-words mb-[60px] md:mb-0">
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-10 md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <h3 className="text-2xl box-border caret-transparent tracking-[1px] leading-[33.6px] break-words font-dm_serif_display md:text-[40px] md:leading-[56px]">
                    <a
                      href="/contact/"
                      title="Let's chat."
                      className="text-white text-2xl box-border caret-transparent leading-[33.6px] break-words md:text-[40px] md:leading-[56px]"
                    >
                      <span className="text-2xl box-border caret-transparent leading-[33.6px] break-words md:text-[40px] md:leading-[56px]">
                        Let&#39;s chat.
                      </span>
                    </a>
                  </h3>
                </div>
              </div>
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-0 md:text-[17px] md:leading-[30.6px] md:mb-[50px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words text-left md:text-[17px] md:leading-[30.6px]">
                    <a
                      href="/contact"
                      className="relative text-white text-[10.7px] font-extrabold box-border caret-transparent inline-block h-[150px] leading-[18px] break-words uppercase w-[150px] px-6 py-3 rounded-bl rounded-br rounded-tl rounded-tr before:accent-auto before:bg-[url('https://www.hitt.com/wp-content/themes/beaverwarrior/assets/icons/Contact_us_today.svg')] before:box-border before:caret-transparent before:text-white before:block before:text-[10.7px] before:not-italic before:normal-nums before:font-extrabold before:h-[150px] before:tracking-[normal] before:leading-[18px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:absolute before:text-left before:indent-[0px] before:uppercase before:visible before:w-[150px] before:mx-auto before:border-separate before:top-[0%] before:inset-x-0 before:font-urbanist after:accent-auto after:bg-[url('https://www.hitt.com/wp-content/themes/beaverwarrior/assets/icons/Arrow_Icon.svg')] after:bg-no-repeat after:bg-size-[100%] after:box-border after:caret-transparent after:text-white after:block after:text-[10.7px] after:not-italic after:normal-nums after:font-extrabold after:h-[156px] after:tracking-[normal] after:leading-[0px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:absolute after:text-left after:indent-[0px] after:uppercase after:translate-y-[-78px] after:visible after:w-full after:mx-auto after:border-separate after:top-2/4 after:inset-x-0 after:font-urbanist"
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="box-border caret-transparent float-left max-w-full min-h-px break-words w-full mx-auto md:max-w-none md:w-[17%] md:mx-0 before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
            <div className="box-border caret-transparent break-words">
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-5 md:text-[17px] md:leading-[30.6px] md:mb-[15px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-white/60 text-[13px] font-black box-border caret-transparent tracking-[1.3px] leading-[23.4px] break-words uppercase">
                    <p className="box-border caret-transparent break-words">
                      Work With HITT
                    </p>
                  </div>
                </div>
              </div>
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                    <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                      <FooterLinks
                        links={[
                          {
                            href: "https://www.hitt.com/careers/",
                            text: "Careers at HITT",
                          },
                          {
                            href: "https://www.hitt.com/subcontractors/",
                            text: "Subcontractors",
                          },
                        ]}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] max-w-full break-words m-auto border-t-transparent border-t-[60px] md:text-[17px] md:leading-[30.6px]"></div>
                </div>
              </div>
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-5 md:text-[17px] md:leading-[30.6px] md:mb-[15px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-white/60 text-[13px] font-black box-border caret-transparent tracking-[1.3px] leading-[23.4px] break-words uppercase">
                    <p className="box-border caret-transparent break-words">
                      Learn More
                    </p>
                  </div>
                </div>
              </div>
              <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                    <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                      <FooterLinks
                        links={[
                          {
                            href: "https://www.hitt.com/locations/",
                            text: "Locations",
                          },
                          {
                            href: "https://www.hitt.com/who-we-are/",
                            text: "Who We Are",
                          },
                        ]}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
