export const ExpertsSection = () => {
  return (
    <div className="box-border caret-transparent break-words mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
      <div className="relative items-center box-border caret-transparent flex justify-center break-words pt-0 md:pt-[50px]">
        <div className="box-border caret-transparent grow max-w-full break-words w-full mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
          <div className="box-border caret-transparent break-words before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
            <div className="box-border caret-transparent clear-both float-none min-h-px break-words w-auto mx-auto md:clear-none md:float-left md:w-full md:mx-0 before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
              <div className="box-border caret-transparent break-words">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-0 md:text-[17px] md:leading-[30.6px] md:mb-[-100px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                    <section className="relative text-base box-border caret-transparent h-[180px] leading-[28.8px] break-words overflow-hidden md:text-[17px] md:h-[303px] md:leading-[30.6px]">
                      <div className="absolute text-base box-border caret-transparent leading-[28.8px] break-words top-0 md:text-[17px] md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent flex leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                          <span className="text-base box-border caret-transparent flex leading-[28.8px] break-words translate-x-[-18.8%] z-[-1] md:text-[17px] md:leading-[30.6px] md:translate-x-[-16.8%]">
                            <span className="text-gray-500/30 text-[140px] box-border caret-transparent block tracking-[5.6px] leading-[140px] break-words text-center text-nowrap w-fit mr-[50px] font-dm_serif_display md:text-[280px] md:tracking-[11.2px] md:leading-[280px]">
                              Our Experts
                            </span>
                            <span className="text-gray-500/30 text-[140px] box-border caret-transparent block tracking-[5.6px] leading-[140px] break-words text-center text-nowrap w-fit mr-[50px] font-dm_serif_display md:text-[280px] md:tracking-[11.2px] md:leading-[280px]">
                              Our Experts
                            </span>
                            <span className="text-gray-500/30 text-[140px] box-border caret-transparent block tracking-[5.6px] leading-[140px] break-words text-center text-nowrap w-fit mr-[50px] font-dm_serif_display md:text-[280px] md:tracking-[11.2px] md:leading-[280px]">
                              Our Experts
                            </span>
                            <span className="text-gray-500/30 text-[140px] box-border caret-transparent block tracking-[5.6px] leading-[140px] break-words text-center text-nowrap w-fit mr-[50px] font-dm_serif_display md:text-[280px] md:tracking-[11.2px] md:leading-[280px]">
                              Our Experts
                            </span>
                          </span>
                        </div>
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
