import { ContactForm } from "@/sections/ContactSection/components/ContactForm";

export const ContactSection = () => {
  return (
    <div className="box-border caret-transparent break-words mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
      <div className="relative items-center box-border caret-transparent flex justify-center break-words pt-5 pb-[100px] px-5 md:px-[50px] md:py-[75px]">
        <div className="box-border caret-transparent grow max-w-[1140px] break-words mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
          <div className="box-border caret-transparent block flex-wrap break-words w-full md:flex">
            <div className="box-border caret-transparent clear-both flex grow-0 float-none max-w-full min-h-px min-w-0 break-words w-full mx-auto md:clear-none md:grow md:float-left md:max-w-none md:min-w-[auto] md:w-2/5 md:mx-0">
              <div className="box-border caret-transparent flex flex-col grow justify-center max-w-full min-w-px break-words w-full">
                <div className="box-border caret-transparent break-words w-full before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
                  <div className="box-border caret-transparent clear-both flex grow float-none min-h-px break-words w-auto mx-auto md:clear-none md:float-left md:w-full md:mx-0">
                    <div className="box-border caret-transparent flex flex-col grow justify-center max-w-full min-w-px break-words w-full">
                      <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                          <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                            <h2 className="text-[28px] box-border caret-transparent tracking-[1px] leading-[39.2px] break-words my-[25px] font-dm_serif_display md:text-[50px] md:leading-[55px]">
                              Contact Us
                            </h2>
                          </div>
                        </div>
                      </div>
                      <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-5 md:text-[17px] md:leading-[30.6px] md:mb-[30px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                          <div className="box-border caret-transparent tracking-[0.64px] leading-[30px] break-words">
                            <p className="box-border caret-transparent break-words">
                              If you&#39;re looking for a construction company
                              in Los Angeles, and you’d like to work with HITT,
                              or if you simply have a question, we’d love to
                              hear from you!
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="box-border caret-transparent break-words w-full before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
                  <div className="box-border caret-transparent clear-both flex grow float-none min-h-px break-words w-auto mx-auto md:clear-none md:float-left md:w-full md:mx-0">
                    <div className="box-border caret-transparent flex flex-col grow justify-center mb-[-50px] max-w-full min-w-px break-words w-full md:mb-0">
                      <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words mb-5 md:text-[17px] md:leading-[30.6px] md:mb-0 before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                          <div className="text-base box-border caret-transparent leading-[28.8px] break-words text-left md:text-[17px] md:leading-[30.6px]">
                            <a
                              href="tel://480.785.9911"
                              className="text-gray-500 text-[13px] font-extrabold bg-transparent box-border caret-transparent inline-block tracking-[1.3px] leading-[18px] break-words uppercase border rounded-bl rounded-br rounded-tl rounded-tr border-solid border-transparent"
                            >
                              <span className="box-border caret-transparent break-words">
                                424.326.1042
                              </span>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                          <div className="text-base box-border caret-transparent leading-[28.8px] break-words text-left md:text-[17px] md:leading-[30.6px]">
                            <a
                              href="https://maps.app.goo.gl/7KvWapwVuRTYhxHX7"
                              className="text-gray-500 text-[13px] font-extrabold bg-transparent box-border caret-transparent inline-block tracking-[1.3px] leading-[18px] break-words uppercase border rounded-bl rounded-br rounded-tl rounded-tr border-solid border-transparent"
                            >
                              <span className="box-border caret-transparent break-words">
                                2150 Park Place, Suite 100, El Segundo, CA 90245
                              </span>
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="box-border caret-transparent clear-both flex grow-0 float-none min-h-px min-w-0 break-words w-full mx-auto md:clear-none md:grow md:float-left md:min-w-[auto] md:w-3/5 md:mx-0">
              <div className="bg-black box-border caret-transparent flex flex-col grow justify-center max-w-full min-w-px break-words w-full ml-0 mt-[100px] pt-[50px] pb-[30px] px-[11px] md:ml-[100px] md:mt-0 md:p-[60px]">
                <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                    <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                      <p className="text-base box-border caret-transparent tracking-[0.8px] leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]"></p>
                      <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]"></div>
                        <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]">
                          <p className="text-base box-border caret-transparent tracking-[0.8px] leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]"></p>
                        </div>
                        <ContactForm />
                      </div>
                      <iframe
                        src="about://blank"
                        name="gform_ajax_frame_7"
                        title="This iframe contains the logic required to handle Ajax powered Gravity Forms."
                        className="text-base box-border caret-transparent hidden h-0 leading-[28.8px] max-w-full break-words w-0 border-zinc-100 md:text-[17px] md:leading-[30.6px]"
                      ></iframe>
                      <p className="text-base box-border caret-transparent tracking-[0.8px] leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px]"></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
