import { DesktopNavbar } from "@/sections/Header/components/DesktopNavbar";
import { MobileNavbar } from "@/sections/Header/components/MobileNavbar";

export const Header = () => {
  return (
    <header
      role="banner"
      className="fixed box-border caret-transparent break-words w-full z-[100] top-0 inset-x-0"
    >
      <div className="box-border caret-transparent break-words mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
        <div className="relative items-center box-border caret-transparent flex justify-center break-words">
          <div className="box-border caret-transparent grow max-w-full break-words w-full mx-auto before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
            <div className="box-border caret-transparent break-words before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
              <div className="box-border caret-transparent clear-both float-none min-h-px break-words w-auto mx-auto md:clear-none md:float-left md:w-full md:mx-0 before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist">
                <div className="box-border caret-transparent break-words">
                  <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                    <div className="text-base box-border caret-transparent leading-[28.8px] break-words md:text-[17px] md:leading-[30.6px] before:accent-auto before:box-border before:caret-transparent before:text-black before:table before:text-base before:not-italic before:normal-nums before:font-normal before:tracking-[normal] before:leading-[28.8px] before:list-outside before:list-disc before:break-words before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-urbanist before:md:text-[17px] before:md:leading-[30.6px] after:accent-auto after:box-border after:caret-transparent after:clear-both after:text-black after:table after:text-base after:not-italic after:normal-nums after:font-normal after:tracking-[normal] after:leading-[28.8px] after:list-outside after:list-disc after:break-words after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:visible after:border-separate after:font-urbanist after:md:text-[17px] after:md:leading-[30.6px]">
                      <header className="absolute text-base box-border caret-transparent leading-[28.8px] break-words w-full z-[888] left-0 top-0 md:text-[17px] md:leading-[30.6px]">
                        <DesktopNavbar />
                        <MobileNavbar />
                        <div className="absolute text-base bg-zinc-100 box-border caret-transparent hidden h-[5px] leading-[28.8px] break-words w-full z-[-2] left-0 top-full md:text-[17px] md:leading-[30.6px]">
                          <div className="text-base bg-pink-600 box-border caret-transparent h-full leading-[28.8px] break-words w-[0%] md:text-[17px] md:leading-[30.6px]"></div>
                        </div>
                      </header>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};
